# Generated by Django 5.0.3 on 2024-03-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_registration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='vendor_application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
