# Generated by Django 5.0.3 on 2024-03-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_registration_vendor_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
