# Generated by Django 5.0.3 on 2024-03-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_registration_otp_expiry_alter_registration_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='otp_expiry',
        ),
        migrations.AlterField(
            model_name='registration',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
