# Generated by Django 5.0.3 on 2024-03-15 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_remove_registration_otp_expiry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="business_description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registration",
            name="business_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registration",
            name="location",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registration",
            name="registering_body",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registration",
            name="registration_no",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registration",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
